### ISSUE TITLE
Error: not found: javac.exe

### ISSUE THREAD

**Issue by rsmolkin** [morgdenn/npm-cflint#1]
Hi, I just tried this, getting an error:
Error: not found: javac.exe

I can get CFLint working inside VSCode, but only if I don't specify the .cflintrc file.  I tried putting in the default one, or one that should exclude some rules (I may have the format wrong...)
```
{
  "output" : [ ],
  "rule" : [ ],
  "excludes" : [ 
    {
      "code" : "VAR_HAS_PREFIX_OR_POSTFIX"
    },
    {
      "code" : "MISSING_VAR"
    },
    {
      "code" : "VAR_INVALID_NAME"
    },
    {
      "code" : "MISSING_VAR"
    },
    {
      "code" : "FUNCTION_TOO_COMPLEX"
    }
  ],
  "includes" : [ ],
  "inheritParent" : false,
  "inheritPlugins" : true
}

**Comment by KamasamaK** [comment]
@rsmolkin Your .cflintrc file looks fine, but note that the `output` and `inheritPlugins` properties are deprecated and can safely be removed. If you're having an issue with the CFLint extension for VS Code, please file an [issue](https://github.com/KamasamaK/vscode-cflint/issues) there.

As for not finding javac.exe, this sounds like it's probably an issue with "find-java-home" not working properly. I recall having some issue using it while developing my extension, and chose to implement it myself. There is an [issue](https://github.com/ditinc/linter-cflint/issues/24) for Atom's linter-cflint that seems to contain the same error.

**Comment by rsmolkin** [comment]
Thank you.  I opened a ticket there too (https://github.com/cflint/CFLint/issues/485).  I thought the reason it doesn't work maybe the .cflintrc file format was wrong somehow.  I just simplified it even further by removing the ones you say are deprecated, but that doesn't seem to help either.
```{
  "rule" : [ ],
  "excludes" : [
    {"code" : "VAR_HAS_PREFIX_OR_POSTFIX"},
    {"code" : "MISSING_VAR"},
    {"code" : "VAR_INVALID_NAME"},
    {"code" : "MISSING_VAR"},
    {"code" : "FUNCTION_TOO_COMPLEX"}],
   "inheritParent" : false
}

**Comment by KamasamaK** [comment]
I meant for you to file an [issue](https://github.com/KamasamaK/vscode-cflint/issues) for the repo I linked, which is the one for the extension. It might not be an issue with CFLint itself, so I would want to look at it first. Please also include the extension settings and the version of CFLint you're using.

**Comment by angeloisaac** [comment]
Do you have JDK installed? I had this error myself because I had JRE (java) and not JDK (java + javac).

(I'm thinkin of submitting a fix concerning that in the coming days)

**Comment by morgdenn** [comment]
Hi everyone,

Due to a job change I'm not working with CF anymore. Would any of you be interested in taking over this project?  

thanks,
Morgan.

**Comment by msp1kpj** [comment]
Morgan, 


Sorry to here that you are doing less in CF. I can take this over if you are still looking for someone.

-Ken

**Comment by morgdenn** [comment]
Hi Ken @msp1kpj ,

It is a shame I'm not doing CF anymore, I do miss it.  This is great news that someone will keep it going! I wish I still had time. 

For the moment I've made you a collaborator in the project so I think you should be able to do everything now.  But it might be easier to just fork it, I'm not sure the best way to do this.  You will also need an NPM account to be able to push a new version.   Let me know when you have one and I'll make you a collaborator on the NPM package as well.

If there is anything I can help you with let me know.

Morgan.

**Comment by msp1kpj** [comment]
Hello Morgan @morgdenn ,

I have created a NPM account. @msp1kpj on npm

Ken

**Comment by morgdenn** [comment]
@msp1kpj you should have access to the NPM project as well now.  Try publishing a new version and see how you go.

If you have any problems let me know.

Morgan.

**Comment by msp1kpj** [comment]
Ok thanks
